### ISSUE TITLE
not checking if interface being configured is virtual

### ISSUE THREAD

**Issue by ochko** [reallyenglish/ansible-role-virtual-interface#20]
for physical interface `apply_hostname_if.sh` fails when it tries to do `ifconfig if destroy`, but `/etc/hostname.if` is updated.

**Comment by ochko** [comment]
For OpenBSD we could check interface name. Virtual interfaces are: bridge, carp, enc, etherip, gif, gre, lo, mpe, mpw, pair, pflog, pflow, pfsync, ppp, pppoe, svlan, tap, trunk, tun, vether, vlan, vxlan

But what about FreeBSD and Linux?

**Comment by trombik** [comment]
the best way would be creating a module that manages virtual interfaces (and possibly physical ones). that was my first thought when thinking ways to manage virtual interfaces. but that is also quite a work. writing a parser for `ifconfig`, `ip` and others, would be one thing. implementing idempotency right would be another. do not forget to handle [every keywords](http://man.openbsd.org/ifconfig) to control virtual interfaces.

it would be definitely helpful if the role warned users when one of interface names in the list was not virtual interface. the question is, should it?

to me, the end result looks same. as you cannot validate _before_ the entire `ansible` play runs, the play would fail in the middle of the play. the difference would be, you can tell clearly that the user has failed to pass valid interface names. you deserve obscure error messages when the role name clearly states that it is for virtual interface.

are you willing to maintain lists of virtual interfaces in various platforms?
